name: Train Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Env
        run: |
          echo "Checking environment variables..."
          env

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas joblib

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=file:./mlruns" >> $GITHUB_ENV
          mkdir -p mlruns

      - name: Run MLflow Project
        run: |
          python MLProject/modelling.py 100 10 0.2

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            **/*.joblib
            **/model.pkl
            **/mlruns
