name: CI Diabetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/diabetes_preprocessing.csv"

jobs:
  mlflow-run:
    runs-on: ubuntu-latest

    steps:
      # Set up job
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.12.7
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Set MLflow Tracking URI
      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=http://127.0.0.1:8000"

      # Run MLflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # Run Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Upload to Google Drive
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }} # Mengambil kredensial dari GitHub Secrets
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }} # Mengambil kredensial dari GitHub Secrets
        run: |
          python MLproject/upload_to_gdrive.py
